export const IPC = {
    AI: {
        CHAT: 'ai:chat',
        COMPLETIONS: 'ai:completions',
        EXECUTE: 'ai:execute',
        GET_METRICS: 'ai:get-metrics',
        GET_PROVIDERS: 'ai:get-providers',
        STREAM_START: 'ai:stream-start',
        STREAM_STOP: 'ai:stream-stop',
    },
    BROWSER: {
        CLOSE_TAB: 'browser:close-tab',
        GET_TABS: 'browser:get-tabs',
        GO_BACK: 'browser:go-back',
        GO_FORWARD: 'browser:go-forward',
        NAVIGATE: 'browser:navigate',
        NEW_TAB: 'browser:new-tab',
        OPEN_TAB: 'browser:open-tab',
    },
    CATALOG: {
        BOOKMARK_ADD: 'catalog:bookmark-add',
        DOWNLOAD_QUEUE: 'catalog:download-queue',
        HISTORY_GET: 'catalog:history-get',
    },
    CRAWLER: {
        CANCEL: 'crawler:cancel',
        EXPORT: 'crawler:export',
        GET: 'crawler:get',
        LIST: 'crawler:list',
        START: 'crawler:start',
    },
    DIALOG: {
        OPEN_FILES: 'dialog:open-files',
        OPEN_FOLDER: 'dialog:open-folder',
        READ_DIR_FILES: 'dialog:read-dir-files',
        READ_FILES: 'dialog:read-files',
    },
    HUB: {
        AGENT_STATUS: 'hub:agent-status',
        AUTO_REGISTER: 'hub:auto-register',
        CREATE_AGENT: 'hub:create-agent',
        GET_AGENTS: 'hub:get-agents',
        GET_CLOUD_RESOURCES: 'hub:get-cloud-resources',
        GET_STATS: 'hub:get-stats',
        GET_TOPIC_FILES: 'hub:get-topic-files',
        GET_TOPICS: 'hub:get-topics',
        QUERY: 'hub:query',
        ROUTE_TASK: 'hub:route-task',
        SEARCH_KNOWLEDGE: 'hub:search-knowledge',
    },
    MCP: {
        EXECUTE_TOOL: 'mcp:execute-tool',
        GET_TOOL_SCHEMA: 'mcp:get-tool-schema',
        LIST_TOOLS: 'mcp:list-tools',
        SERVER_STATUS: 'mcp:server-status',
    },
    NETWORK: {
        CLEAR_PROXY: 'network:clear-proxy',
        DNS_LOOKUP: 'network:dns-lookup',
        FETCH: 'network:fetch',
        GET_CONFIG: 'network:get-config',
        GET_CONNECTIONS: 'network:get-connections',
        GET_REPORT: 'network:get-report',
        GET_STATS: 'network:get-stats',
        PROXY_TOGGLE: 'network:proxy-toggle',
        SET_PROXY: 'network:set-proxy',
    },
    PLUGIN: {
        CAPABILITIES: 'plugin:capabilities',
        LOAD: 'plugin:load',
        UNLOAD: 'plugin:unload',
    },
    SEARCH: {
        COMPARE: 'search:compare',
        CRAWL: 'search:crawl',
        DEEP: 'search:deep',
        GET_CONFIG: 'search:get-config',
        INDEX: 'search:index',
        IS_READY: 'search:is-ready',
        LOCAL: 'search:local',
        QUERY: 'search:query',
        SET_CONFIG: 'search:set-config',
        WEB: 'search:web',
    },
    SYSTEM: {
        FILE_DIALOG_OPEN: 'system:file-dialog-open',
        OPEN_EXTERNAL: 'system:open-external',
        TERMINAL_SEND: 'system:terminal-send',
        APP_GET_PATH: 'system:app-get-path',
    },
    TERMINAL: {
        EXECUTE: 'terminal:execute',
        GET_CWD: 'terminal:get-cwd',
        GET_ENV: 'terminal:get-env',
        KILL_PROCESS: 'terminal:kill-process',
        SET_CWD: 'terminal:set-cwd',
        SYSTEM_INFO: 'terminal:system-info',
    },
    PTY: {
        CREATE: 'pty:create',
        WRITE: 'pty:write',
        RESIZE: 'pty:resize',
        KILL: 'pty:kill',
        DATA: 'pty:data',       // main → renderer (push)
        EXIT: 'pty:exit',       // main → renderer (push)
    },
    FILE: {
        LIST: 'file:list',
        READ: 'file:read',
        WRITE: 'file:write',
        DELETE: 'file:delete',
        STAT: 'file:stat',
        OPEN_FOLDER: 'file:open-folder',
    },
    WINDOW: {
        CLOSE: 'window:close',
        MAXIMIZE: 'window:maximize',
        MINIMIZE: 'window:minimize',
    },
    WORKFLOW: {
        CREATE: 'workflow:create',
        EXECUTE: 'workflow:execute',
        GET_EXECUTION: 'workflow:get-execution',
        LIST: 'workflow:list',
        LIST_EXECUTIONS: 'workflow:list-executions',
    },
} as const;

export type IpcChannel = {
    [K in keyof typeof IPC]: (typeof IPC)[K][keyof (typeof IPC)[K]];
}[keyof typeof IPC];